In [2]:
# Step 1: Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
#pip install pandas pyreadstat

In [9]:
# Exporting the Dietary food day 1 data
df_dietary_food_first_day = pd.read_sas('F:\Susanna Course\Capstone_data\DR1IFF_L.xpt', format="xport", encoding="utf-8")

In [ ]:
df_dietary_food_first_day.head(5)

In [ ]:
df_dietary_food_first_day.columns

In [6]:
df_dietary_food_first_day.shape

(100116, 84)

In [10]:
# Renaming the Columns
df_dietary_food_first_day = df_dietary_food_first_day.rename(columns={'SEQN': 'seqn_no', 'WTDRD1': 'survey_wt_day_01','WTDR2D': 'survey_wt_day_02','DR1ILINE':'food_line_no','DR1DRSTZ':'dietary_recall_status','DR1EXMER':'interview_code','DR1CCMNM':'food_no','DR1CCMTX':'food_type','DR1FS':'food_source','DR1IGRMS':'food_gms'})

In [11]:
# Keeping the columns which has meaningful values
df_dietary_food_first_day
columns_to_keep = ['seqn_no','survey_wt_day_01', 'survey_wt_day_02', 'food_line_no','dietary_recall_status', 'interview_code','food_gms']

df_dietary_filtered_day_01 = df_dietary_food_first_day[columns_to_keep]

In [16]:
 # The filtered day_o1 foods Dietary data
df_dietary_filtered_day_01.columns

Index(['seqn_no', 'survey_wt_day_01', 'survey_wt_day_02', 'food_line_no',
       'dietary_recall_status', 'interview_code', 'food_gms'],
      dtype='object')

In [14]:
# Exporting the Dietary food day 2 data
df_dietary_food_second_day = pd.read_sas('F:\Susanna Course\Capstone_data\DR2IFF_L.xpt', format="xport", encoding="utf-8")

In [17]:
df_dietary_food_second_day.shape

(88032, 84)

In [20]:
df_dietary_food_second_day
columns_to_keep = ['SEQN','WTDRD1','WTDR2D','DR2ILINE','DR2DRSTZ','DR2EXMER','DRABF','DRDINT',
                  'DR2FS', 'DR2_040Z', 'DR2IFDCD', 'DR2IGRMS','DR2ICALC', 'DR2IMAGN',
                 'DR2IZINC', 'DR2ICOPP', 'DR2ISODI','DR2IMOIS']
df_dietary_filtered_day_02 = df_dietary_food_second_day[columns_to_keep]

In [21]:
df_dietary_filtered_day_02

,SEQN,WTDRD1,WTDR2D,DR2ILINE,DR2DRSTZ,DR2EXMER,DRABF,DRDINT,DR2FS,DR2_040Z,DR2IFDCD,DR2IGRMS,DR2ICALC,DR2IMAGN,DR2IZINC,DR2ICOPP,DR2ISODI,DR2IMOIS
0,130378.0,61366.555827,70554.222162,1.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
1,130378.0,61366.555827,70554.222162,2.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
2,130378.0,61366.555827,70554.222162,3.0,1.0,49.0,2.0,2.0,1.0,1.0,92103000.0,300.00,12.0,11.0,0.04,0.033,13.0,297.27
3,130378.0,61366.555827,70554.222162,4.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
4,130378.0,61366.555827,70554.222162,5.0,1.0,49.0,2.0,2.0,1.0,1.0,56205000.0,158.00,16.0,19.0,0.77,0.109,387.0,107.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88027,142310.0,47870.215680,51601.585149,6.0,1.0,91.0,2.0,2.0,1.0,1.0,74406010.0,11.33,4.0,1.0,0.02,0.008,116.0,6.20
88028,142310.0,47870.215680,51601.585149,7.0,1.0,91.0,2.0,2.0,1.0,1.0,75204023.0,23.13,7.0,9.0,0.17,0.038,86.0,16.33
88029,142310.0,47870.215680,51601.585149,8.0,1.0,91.0,2.0,2.0,16.0,1.0,53201000.0,40.00,8.0,16.0,0.29,0.129,124.0,1.43
88030,142310.0,47870.215680,51601.585149,9.0,1.0,91.0,2.0,2.0,1.0,1.0,93301110.0,360.00,4.0,5.0,0.16,0.072,6.0,254.86
88031,142310.0,47870.215680,51601.585149,10.0,1.0,91.0,2.0,2.0,16.0,1.0,42112200.0,13.50,7.0,13.0,0.51,0.117,52.0,0.34

In [22]:
# Rename columns
df_dietary_filtered_day_02  = df_dietary_filtered_day_02 .rename(
    columns={'SEQN': 'seqn_no', 'WTDRD1': 'survey_wt_day_01','WTDR2D':'survey_wt_day_02','DR1ILINE':'food_line_no',
             'DR1DRSTZ':'dietary_recall_status','DR1EXMER':'interview_code','DRABF':'breast_fed',
            'DRDINT':'data_participate','DR2FS':'food_source','DR2_040Z':'home_meal','DR2IFDCD':'usda_food_code',
            'DR2IGRMS':'food_gms','DR2ICALC':'calc_mg','DR2IMAGN':'magnesium_mg','DR2IZINC':'zinc_mg', 'DR2ICOPP':'copper_mg',
              'DR2ISODI':'sodium_mg','DR2IMOIS':'moisture_gms'})

In [ ]:
df_dietary_filtered_day_02

In [26]:
# Exporting the Dietary Nutrients intake day  data
df_dietary_nutrient_intake_day_01 = pd.read_sas('F:\Susanna Course\Capstone_data\DR1TOT_L.xpt', format="xport", encoding="utf-8")

In [27]:
df_dietary_nutrient_intake_day_01

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
0,130378.0,6.136656e+04,70554.222162,1.0,73.0,2.0,2.0,40.0,4.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
1,130379.0,3.463806e+04,36505.468348,1.0,73.0,2.0,2.0,19.0,4.0,1.0,...,1.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
2,130380.0,8.472826e+04,103979.190677,1.0,73.0,2.0,2.0,16.0,4.0,1.0,...,NaN,2.0,NaN,2.0,NaN,1.0,4.0,2.0,NaN,2.0
3,130381.0,6.173713e+04,75009.220819,1.0,91.0,2.0,2.0,23.0,5.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
4,130382.0,7.584675e+04,172361.851828,1.0,73.0,2.0,2.0,27.0,6.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8855,142306.0,5.397605e-79,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8856,142307.0,6.606603e+04,70259.160313,1.0,65.0,2.0,2.0,19.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8857,142308.0,5.397605e-79,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8858,142309.0,9.447764e+04,89391.946869,1.0,90.0,2.0,2.0,49.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8859,142310.0,4.787022e+04,51601.585149,1.0,89.0,2.0,2.0,19.0,5.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#export as csv

file_path = "../data/dietary_data/df_dietary_day_01.csv" 

try:
    df_dietary_filtered_day_01.to_csv(file_path, index=False, encoding='utf-8')
    print(f"DataFrame successfully saved to: {file_path}")
except Exception as e:
    print(f"Error saving DataFrame to CSV: {e}")

In [ ]:
# Export to DataBase
from sqlalchemy import create_engine, types

In [ ]:
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']

# Now building the URL with the values from the .env file
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

engine = create_engine(url, echo=False)

In [ ]:
df_dietary_filtered_day_01(name = 'demographic_data', con=engine, schema='capstone_group_3',if_exists='replace',index=False)