In [ ]:
# Step 1: Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Export to DataBase
from sqlalchemy import create_engine, types

In [56]:
#pip install pandas pyreadstat

## Dietary food data for Day 01

In [138]:
# Exporting the Dietary food day 1 data
df_dietary_food_first_day = pd.read_sas('F:\Susanna Course\Capstone_data\DR1IFF_L.xpt', format="xport", encoding="utf-8")

In [ ]:
df_dietary_food_first_day.head(5)

In [140]:
df_dietary_food_first_day.shape

(100116, 84)

In [ ]:
# Renaming the Columns
df_dietary_food_first_day = df_dietary_food_first_day.rename(columns={'SEQN': 'seqn_no', 'WTDRD1': 'survey_wt_day_01','WTDR2D': 'survey_wt_day_02','DR1ILINE':'food_line_no','DR1DRSTZ':'dietary_recall_status','DR1EXMER':'interview_code','DR1CCMNM':'food_no','DR1CCMTX':'food_type','DR1FS':'food_source','DR1IGRMS':'food_gms'})

In [142]:
df_dietary_food_first_day

,seqn_no,survey_wt_day_01,survey_wt_day_02,food_line_no,dietary_recall_status,interview_code,DRABF,DRDINT,DR1DBIH,DR1DAY,...,DR1IM181,DR1IM201,DR1IM221,DR1IP182,DR1IP183,DR1IP184,DR1IP204,DR1IP205,DR1IP225,DR1IP226
0,130378.0,61366.555827,70554.222162,1.0,1.0,73.0,2.0,2.0,40.0,4.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
1,130378.0,61366.555827,70554.222162,2.0,1.0,73.0,2.0,2.0,40.0,4.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
2,130378.0,61366.555827,70554.222162,3.0,1.0,73.0,2.0,2.0,40.0,4.0,...,5.397605e-79,5.397605e-79,5.397605e-79,3.000000e-03,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
3,130378.0,61366.555827,70554.222162,4.0,1.0,73.0,2.0,2.0,40.0,4.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
4,130378.0,61366.555827,70554.222162,5.0,1.0,73.0,2.0,2.0,40.0,4.0,...,6.530000e-01,7.000000e-03,5.397605e-79,1.418000e+00,1.890000e-01,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,1.000000e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100111,142310.0,47870.215680,51601.585149,14.0,1.0,89.0,2.0,2.0,19.0,5.0,...,1.400000e-02,5.397605e-79,5.397605e-79,6.100000e-02,1.400000e-02,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
100112,142310.0,47870.215680,51601.585149,15.0,1.0,89.0,2.0,2.0,19.0,5.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
100113,142310.0,47870.215680,51601.585149,16.0,1.0,89.0,2.0,2.0,19.0,5.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
100114,142310.0,47870.215680,51601.585149,17.0,1.0,89.0,2.0,2.0,19.0,5.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
100115,142310.0,47870.215680,51601.585149,18.0,1.0,89.0,2.0,2.0,19.0,5.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79

In [ ]:
# Keeping the columns which has meaningful values
df_dietary_food_first_day
columns_to_keep = ['seqn_no','survey_wt_day_01', 'survey_wt_day_02', 'food_line_no','dietary_recall_status','food_gms']

df_dietary_filtered_day_01 = df_dietary_food_first_day[columns_to_keep]

In [ ]:
 # The filtered day_o1 foods Dietary data
df_dietary_filtered_day_01

In [134]:
# Group by 'seqn_no' and sum the 'food_gms' for each participant
agg_df = df_dietary_filtered_day_01.groupby('seqn_no')['food_gms'].sum().reset_index()

In [136]:
agg_df

       seqn_no  food_gms
0     130378.0   3662.08
1     130379.0   4697.95
2     130380.0   4537.50
3     130381.0   1995.40
4     130382.0   1533.98
...        ...       ...
6746  142303.0   1966.30
6747  142304.0   1454.75
6748  142307.0   2675.00
6749  142309.0   2196.00
6750  142310.0   1437.99

[6751 rows x 2 columns]

The average daily calorie needs vary widely:
Men: 2,000 to 2,500 calories per day.
Women: 1,800 to 2,200 calories per day.
Children and Adolescents: Their needs range from 1,200 to 2,500 calories depending on age and activity level.
Physically active individuals: May require 2,500–3,000 calories or more.
These calories are distributed across macronutrients like carbohydrates, proteins, and fats.

In [ ]:
#export as csv

file_path = "../data/dietary_data/dietary_data_day_01.csv" 

try:
    df_dietary_filtered_day_01.to_csv(file_path, index=False, encoding='utf-8')
    print(f"DataFrame successfully saved to: {file_path}")
except Exception as e:
    print(f"Error saving DataFrame to CSV: {e}")

In [104]:
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']

# Now building the URL with the values from the .env file
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

engine = create_engine(url, echo=False)

In [107]:
# creating table in the database 

df_dietary_filtered_day_01.to_sql(name = 'dietary_food_data_01', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

116

## Dietary food data for Day 02

In [14]:
# Exporting the Dietary food day 2 data
df_dietary_food_second_day = pd.read_sas('F:\Susanna Course\Capstone_data\DR2IFF_L.xpt', format="xport", encoding="utf-8")

In [15]:
df_dietary_food_second_day.shape

(88032, 84)

In [126]:
df_dietary_food_second_day
columns_to_keep = ['SEQN','WTDRD1','WTDR2D','DR2ILINE','DR2DRSTZ','DR2EXMER','DRABF','DRDINT',
                  'DR2FS', 'DR2_040Z', 'DR2IFDCD', 'DR2IGRMS','DR2ICALC', 'DR2IMAGN',
                 'DR2IZINC', 'DR2ICOPP', 'DR2ISODI','DR2IMOIS']
df_dietary_filtered_day_02 = df_dietary_food_second_day[columns_to_keep]

In [17]:
df_dietary_filtered_day_02

,SEQN,WTDRD1,WTDR2D,DR2ILINE,DR2DRSTZ,DR2EXMER,DRABF,DRDINT,DR2FS,DR2_040Z,DR2IFDCD,DR2IGRMS,DR2ICALC,DR2IMAGN,DR2IZINC,DR2ICOPP,DR2ISODI,DR2IMOIS
0,130378.0,61366.555827,70554.222162,1.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
1,130378.0,61366.555827,70554.222162,2.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
2,130378.0,61366.555827,70554.222162,3.0,1.0,49.0,2.0,2.0,1.0,1.0,92103000.0,300.00,12.0,11.0,0.04,0.033,13.0,297.27
3,130378.0,61366.555827,70554.222162,4.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
4,130378.0,61366.555827,70554.222162,5.0,1.0,49.0,2.0,2.0,1.0,1.0,56205000.0,158.00,16.0,19.0,0.77,0.109,387.0,107.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88027,142310.0,47870.215680,51601.585149,6.0,1.0,91.0,2.0,2.0,1.0,1.0,74406010.0,11.33,4.0,1.0,0.02,0.008,116.0,6.20
88028,142310.0,47870.215680,51601.585149,7.0,1.0,91.0,2.0,2.0,1.0,1.0,75204023.0,23.13,7.0,9.0,0.17,0.038,86.0,16.33
88029,142310.0,47870.215680,51601.585149,8.0,1.0,91.0,2.0,2.0,16.0,1.0,53201000.0,40.00,8.0,16.0,0.29,0.129,124.0,1.43
88030,142310.0,47870.215680,51601.585149,9.0,1.0,91.0,2.0,2.0,1.0,1.0,93301110.0,360.00,4.0,5.0,0.16,0.072,6.0,254.86
88031,142310.0,47870.215680,51601.585149,10.0,1.0,91.0,2.0,2.0,16.0,1.0,42112200.0,13.50,7.0,13.0,0.51,0.117,52.0,0.34

In [127]:
# Rename columns
df_dietary_filtered_day_02  = df_dietary_filtered_day_02 .rename(
    columns={'SEQN': 'seqn_no', 'WTDRD1': 'survey_wt_day_01','WTDR2D':'survey_wt_day_02','DR1ILINE':'food_line_no',
             'DR1DRSTZ':'dietary_recall_status','DR1EXMER':'interview_code','DRABF':'breast_fed',
            'DRDINT':'data_participate','DR2FS':'food_source','DR2_040Z':'home_meal','DR2IFDCD':'usda_food_code',
            'DR2IGRMS':'food_gms','DR2ICALC':'calc_mg','DR2IMAGN':'magnesium_mg','DR2IZINC':'zinc_mg', 'DR2ICOPP':'copper_mg',
              'DR2ISODI':'sodium_mg','DR2IMOIS':'moisture_gms'})

In [128]:
df_dietary_filtered_day_02

,seqn_no,survey_wt_day_01,survey_wt_day_02,DR2ILINE,DR2DRSTZ,DR2EXMER,breast_fed,data_participate,food_source,home_meal,usda_food_code,food_gms,calc_mg,magnesium_mg,zinc_mg,copper_mg,sodium_mg,moisture_gms
0,130378.0,61366.555827,70554.222162,1.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
1,130378.0,61366.555827,70554.222162,2.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
2,130378.0,61366.555827,70554.222162,3.0,1.0,49.0,2.0,2.0,1.0,1.0,92103000.0,300.00,12.0,11.0,0.04,0.033,13.0,297.27
3,130378.0,61366.555827,70554.222162,4.0,1.0,49.0,2.0,2.0,NaN,1.0,94000100.0,240.00,7.0,2.0,0.02,0.024,10.0,239.76
4,130378.0,61366.555827,70554.222162,5.0,1.0,49.0,2.0,2.0,1.0,1.0,56205000.0,158.00,16.0,19.0,0.77,0.109,387.0,107.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88027,142310.0,47870.215680,51601.585149,6.0,1.0,91.0,2.0,2.0,1.0,1.0,74406010.0,11.33,4.0,1.0,0.02,0.008,116.0,6.20
88028,142310.0,47870.215680,51601.585149,7.0,1.0,91.0,2.0,2.0,1.0,1.0,75204023.0,23.13,7.0,9.0,0.17,0.038,86.0,16.33
88029,142310.0,47870.215680,51601.585149,8.0,1.0,91.0,2.0,2.0,16.0,1.0,53201000.0,40.00,8.0,16.0,0.29,0.129,124.0,1.43
88030,142310.0,47870.215680,51601.585149,9.0,1.0,91.0,2.0,2.0,1.0,1.0,93301110.0,360.00,4.0,5.0,0.16,0.072,6.0,254.86
88031,142310.0,47870.215680,51601.585149,10.0,1.0,91.0,2.0,2.0,16.0,1.0,42112200.0,13.50,7.0,13.0,0.51,0.117,52.0,0.34

In [28]:
#export as csv

file_path = "../data/dietary_data/dietary_food_data_day_02.csv" 

try:
    df_dietary_filtered_day_02.to_csv(file_path, index=False, encoding='utf-8')
    print(f"DataFrame successfully saved to: {file_path}")
except Exception as e:
    print(f"Error saving DataFrame to CSV: {e}")

DataFrame successfully saved to: ../data/dietary_data/dietary_food_data_day_02.csv

In [ ]:
# creating table and adding data to the database

df_dietary_filtered_day_02.to_sql(name = 'dietary_food_data_02', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

32

## Dietary Nutrient Intake data for Day 01

In [33]:
# Exporting the Dietary Nutrients intake day  data
df_dietary_nutrient_intake_day_01 = pd.read_sas('F:\Susanna Course\Capstone_data\DR1TOT_L.xpt', format="xport", encoding="utf-8")

In [60]:
df_dietary_nutrient_intake_day_01.shape

(8860, 168)

In [129]:
# List of relevant nutrient columns which could potentially be related to the research question
nutrient_columns = [
    'SEQN',
    'DR1TKCAL', 'DR1TPROT', 'DR1TCARB','DR1TSUGR','DR1TFIBE', 'DR1TTFAT',
     'DR1TSFAT','DR1TMFAT','DR1TPFAT','DR1TCHOL','DR1TSODI','DR1TPOTA','DR1TMOIS',
    'DR1TVC','DR1TVD','DR1TVK','DR1TCALC'
    ]

In [130]:
# Filter the dataframe to keep only the relevant columns
df_nutrients_day01 = df_dietary_nutrient_intake_day_01[nutrient_columns]

In [131]:
# Rename columns
df_nutrients  = df_nutrients.rename(
    columns={'SEQN': 'seqn_no',
             'DR1TKCAL':'energy_kcal','DR1TPROT':'protein_gms','DR1TCARB':'carbohydrate_gms','DR1TTFAT':'total_fat_gms',
             'DR1TSUGR': 'total_sugars_gms','DR1TFIBE':'dietary_fiber_gms','DR1TSFAT':'saturated_fats_gms', 'DR1TMFAT':'mono_saturated_fats_gms',
             'DR1TPFAT':'poly_saturated_fats_gms','DR1TCHOL':'cholestrol_gms','DR1TCALC':'calcium_mg',
             'DR1TSODI':'sodium_mg','DR1TPOTA':'potassium_mg','DR1TCAFF':'caffeine_mg','DR1TALCO':'alcohol_gms',
              'DR1TMOIS':'moisture_gms','DR1TVC':'vitaminC_mg','DR1TVD':'vitaminD_mcg','DR1TVK':'vitaK_mcg'})

In [132]:
df_nutrients_day01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8860 entries, 0 to 8859
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      8860 non-null   float64
 1   DR1TKCAL  6694 non-null   float64
 2   DR1TPROT  6694 non-null   float64
 3   DR1TCARB  6694 non-null   float64
 4   DR1TSUGR  6694 non-null   float64
 5   DR1TFIBE  6694 non-null   float64
 6   DR1TTFAT  6694 non-null   float64
 7   DR1TSFAT  6694 non-null   float64
 8   DR1TMFAT  6694 non-null   float64
 9   DR1TPFAT  6694 non-null   float64
 10  DR1TCHOL  6694 non-null   float64
 11  DR1TSODI  6694 non-null   float64
 12  DR1TPOTA  6694 non-null   float64
 13  DR1TMOIS  6694 non-null   float64
 14  DR1TVC    6694 non-null   float64
 15  DR1TVD    6694 non-null   float64
 16  DR1TVK    6694 non-null   float64
 17  DR1TCALC  6694 non-null   float64
dtypes: float64(18)
memory usage: 1.2 MB

In [ ]:
# Now changing the data type of 'seqn_no' to int
df_nutrients_day01['seqn_no'] = df_nutrients_day01['seqn_no'].astype(int)

In [ ]:
# Display the first few rows to check the data
df_nutrients_day01.head()

,seqn_no,energy_kcal,protein_gms,carbohydrate_gms,total_sugars_gms,dietary_fiber_gms,total_fat_gms,saturated_fats_gms,mono_saturated_fats_gms,poly_saturated_fats_gms,cholestrol_gms,sodium_mg,potassium_mg,moisture_gms,vitaminC_mg,vitaminD_mcg,vitaK_mcg,calcium_mg
0,130378,1740.0,80.46,169.66,43.71,10.1,55.07,21.000,17.040,11.401,274.0,2628.0,1917.0,3306.98,22.0,0.2,115.0,693.0
1,130379,2741.0,86.45,314.86,113.58,29.6,67.18,14.544,19.386,25.622,131.0,5635.0,5470.0,4115.06,222.2,0.4,118.1,674.0
2,130380,1995.0,69.86,281.67,114.66,21.1,65.38,26.936,18.638,11.687,270.0,2890.0,2116.0,4103.91,197.3,5.4,44.2,1559.0
3,130381,1676.0,54.11,224.98,117.83,11.5,63.57,22.004,17.342,16.090,188.0,2777.0,2229.0,1634.89,246.7,6.9,133.7,1409.0
4,130382,1222.0,29.14,194.30,112.99,13.8,39.80,8.242,14.795,13.283,28.0,1288.0,1209.0,1262.74,115.9,0.3,24.8,380.0

In [ ]:
#export as csv

file_path = "../data/dietary_data/dietary_nutrient_data_01.csv" 

try:
    df_nutrients_day01.to_csv(file_path, index=False, encoding='utf-8')
    print(f"DataFrame successfully saved to: {file_path}")
except Exception as e:
    print(f"Error saving DataFrame to CSV: {e}")

DataFrame successfully saved to: ../data/dietary_data/dietary_nutrient_data_01.csv

In [ ]:
df_nutrients_day01.to_sql(name = 'dietary_nutrient_data_01', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

860

## Dietary Nutrient Intake data for Day 02

In [108]:
# Exporting the Dietary Nutrients intake day  data
df_dietary_nutrient_intake_day_02 = pd.read_sas('F:\Susanna Course\Capstone_data\DR2TOT_L.xpt', format="xport", encoding="utf-8")

In [110]:
df_dietary_nutrient_intake_day_02.shape

(8860, 85)

In [111]:
# List of relevant nutrient columns which could potentially be related to the research question
nutrient_columns = [
    'SEQN',
    'DR1TKCAL', 'DR1TPROT', 'DR1TCARB','DR1TSUGR','DR1TFIBE', 'DR1TTFAT',
     'DR1TSFAT','DR1TMFAT','DR1TPFAT','DR1TCHOL','DR1TSODI','DR1TPOTA','DR1TMOIS',
    'DR1TVC','DR1TVD','DR1TVK','DR1TCALC'
    ]

In [117]:
# Filter the dataframe to keep only the relevant columns
df_nutrients_day02 = df_dietary_nutrient_intake_day_01[nutrient_columns]

In [118]:
# Rename columns
df_nutrients_day02  = df_nutrients_day02.rename(
    columns={'SEQN': 'seqn_no',
             'DR1TKCAL':'energy_kcal','DR1TPROT':'protein_gms','DR1TCARB':'carbohydrate_gms','DR1TTFAT':'total_fat_gms',
             'DR1TSUGR': 'total_sugars_gms','DR1TFIBE':'dietary_fiber_gms','DR1TSFAT':'saturated_fats_gms', 'DR1TMFAT':'mono_saturated_fats_gms',
             'DR1TPFAT':'poly_saturated_fats_gms','DR1TCHOL':'cholestrol_gms','DR1TCALC':'calcium_mg',
             'DR1TSODI':'sodium_mg','DR1TPOTA':'potassium_mg','DR1TCAFF':'caffeine_mg','DR1TALCO':'alcohol_gms',
              'DR1TMOIS':'moisture_gms','DR1TVC':'vitaminC_mg','DR1TVD':'vitaminD_mcg','DR1TVK':'vitaK_mcg'})

In [ ]:
df_nutrients_day02.info()

In [120]:
# Now changing the data type of 'seqn_no' to int
df_nutrients_day02['seqn_no'] = df_nutrients_day02['seqn_no'].astype(int)

In [121]:
df_nutrients_day02.head()

,seqn_no,energy_kcal,protein_gms,carbohydrate_gms,total_sugars_gms,dietary_fiber_gms,total_fat_gms,saturated_fats_gms,mono_saturated_fats_gms,poly_saturated_fats_gms,cholestrol_gms,sodium_mg,potassium_mg,moisture_gms,vitaminC_mg,vitaminD_mcg,vitaK_mcg,calcium_mg
0,130378,1740.0,80.46,169.66,43.71,10.1,55.07,21.000,17.040,11.401,274.0,2628.0,1917.0,3306.98,22.0,0.2,115.0,693.0
1,130379,2741.0,86.45,314.86,113.58,29.6,67.18,14.544,19.386,25.622,131.0,5635.0,5470.0,4115.06,222.2,0.4,118.1,674.0
2,130380,1995.0,69.86,281.67,114.66,21.1,65.38,26.936,18.638,11.687,270.0,2890.0,2116.0,4103.91,197.3,5.4,44.2,1559.0
3,130381,1676.0,54.11,224.98,117.83,11.5,63.57,22.004,17.342,16.090,188.0,2777.0,2229.0,1634.89,246.7,6.9,133.7,1409.0
4,130382,1222.0,29.14,194.30,112.99,13.8,39.80,8.242,14.795,13.283,28.0,1288.0,1209.0,1262.74,115.9,0.3,24.8,380.0

In [122]:
#export as csv

file_path = "../data/dietary_data/dietary_nutrient_data_02.csv" 

try:
    df_nutrients_day02.to_csv(file_path, index=False, encoding='utf-8')
    print(f"DataFrame successfully saved to: {file_path}")
except Exception as e:
    print(f"Error saving DataFrame to CSV: {e}")

DataFrame successfully saved to: ../data/dietary_data/dietary_nutrient_data_02.csv

In [133]:
# Now building the URL with the values from the .env file
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

engine = create_engine(url, echo=False) 
df_nutrients_day02.to_sql(name = 'dietary_nutrient_data_02', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

860

In [ ]:
# ALTER DEFAULT PRIVILEGES IN SCHEMA capstone_group_3
# GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO zhenyang;