In [1]:
# Step 1: Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Export to DataBase
from sqlalchemy import create_engine, types

#  Physical activity data from Questionnaire

In [41]:
# Exporting the Dietary Nutrients intake day  data
df_quest_physical_activity = pd.read_sas('..\data\Quest_data\PAQ_L.xpt', format="xport", encoding="utf-8")

In [42]:
# Step 1: Rename the columns

df_quest_physical_activity = df_quest_physical_activity.rename(columns={
    'SEQN': 'seqn_no',
    'PAD790Q': 'mod_LTPA_count', # moderate LTPA - leisure time physical activity
    'PAD790U': 'mod_LTPA_unit',
    'PAD800': 'mod_LTPA_minutes',
    'PAD810Q': 'vig_LTPA_count', # vigorous LTPA
    'PAD810U': 'vig_LTPA_unit',
    'PAD820': 'vig_LTPA_minutes',
    'PAD680': 'sed_minutes' # Sedantary activity minutes excluding sleep
})

# Step 2: Changing the data type of 'seqn_no' to int
df_quest_physical_activity['seqn_no'] = df_quest_physical_activity['seqn_no'].astype(int)

In [ ]:
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']

153

In [ ]:

# Now building the URL with the values from the .env file
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

engine = create_engine(url, echo=False) 

df_quest_physical_activity.to_sql(name = 'Quest_physical_activity', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

# Sleep disorder data from Questionnaire

In [89]:
# Exporting sleep disorder data from Questionaire
df_quest_sleep_disorders = pd.read_sas('..\data\Quest_data\SLQ_L.xpt', format="xport", encoding="utf-8")

In [90]:
# Step 1: Rename the columns

df_quest_sleep_disorders = df_quest_sleep_disorders.rename(columns={
    'SEQN': 'seqn_no',
    'SLQ300': 'bedtime_weekday',
    'SLQ310': 'waketime_weekday',
    'SLD012': 'sleep_hrs_weekday', 
    'SLQ320': 'bedtime_weekend',
    'SLQ330': 'waketime_weekend',
    'SLD013': 'sleep_hrs_weekend'
})

# Step 2: Changing the data type of 'seqn_no' to int
df_quest_sleep_disorders['seqn_no'] = df_quest_sleep_disorders['seqn_no'].astype(int)

In [91]:
df_quest_sleep_disorders

,seqn_no,bedtime_weekday,waketime_weekday,sleep_hrs_weekday,bedtime_weekend,waketime_weekend,sleep_hrs_weekend
0,130378,21:30,07:00,9.5,00:00,09:00,9.0
1,130379,21:00,06:00,9.0,21:00,06:00,9.0
2,130380,00:00,08:00,8.0,00:00,09:00,9.0
3,130384,21:30,05:00,7.5,23:00,07:00,8.0
4,130385,22:05,06:15,8.0,22:05,06:15,8.0
...,...,...,...,...,...,...,...
8496,142305,00:00,09:00,9.0,00:00,09:00,9.0
8497,142307,00:00,07:00,7.0,00:00,07:00,7.0
8498,142308,21:30,06:30,9.0,00:00,08:00,8.0
8499,142309,21:00,05:00,8.0,00:00,12:00,12.0
8500,142310,22:00,07:00,9.0,22:00,07:00,9.0

In [92]:
# Equal Weight Average
df_quest_sleep_disorders['avg_sleep_hrs'] = df_quest_sleep_disorders[['sleep_hrs_weekday', 'sleep_hrs_weekend']].mean(axis=1)

In [93]:
df_quest_sleep_disorders

,seqn_no,bedtime_weekday,waketime_weekday,sleep_hrs_weekday,bedtime_weekend,waketime_weekend,sleep_hrs_weekend,avg_sleep_hrs
0,130378,21:30,07:00,9.5,00:00,09:00,9.0,9.25
1,130379,21:00,06:00,9.0,21:00,06:00,9.0,9.00
2,130380,00:00,08:00,8.0,00:00,09:00,9.0,8.50
3,130384,21:30,05:00,7.5,23:00,07:00,8.0,7.75
4,130385,22:05,06:15,8.0,22:05,06:15,8.0,8.00
...,...,...,...,...,...,...,...,...
8496,142305,00:00,09:00,9.0,00:00,09:00,9.0,9.00
8497,142307,00:00,07:00,7.0,00:00,07:00,7.0,7.00
8498,142308,21:30,06:30,9.0,00:00,08:00,8.0,8.50
8499,142309,21:00,05:00,8.0,00:00,12:00,12.0,10.00
8500,142310,22:00,07:00,9.0,22:00,07:00,9.0,9.00

In [94]:
# Now building the URL with the values from the .env file
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

engine = create_engine(url, echo=False) 
df_quest_sleep_disorders.to_sql(name = 'Quest_sleep', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

501